[package]
name = "update-version"
version = "0.0.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
publish = false

[dependencies]
toml = "~0.4"
serde = "~1.0"
serde_derive = "~1.0"
tempdir = "~0.3"
regex = "~1.0"
